(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"2HDM",
  Authors -> {"C. Duhr", "M. Herquet", "C. Degrande", "L. Mason"},
  Version -> "1.2",
  Date -> "03. 2019",
  Institutions -> {"Universite catholique de Louvain (CP3)", "NIKHEF Theory Dept.", "IPPP", "SA-CERN"},
  URLs -> "http://feynrules.phys.ucl.ac.be/view/Main/2HDM",
  Emails -> {"claude.duhr@uclouvain.be", "mherquet@nikhef.nl", "celine.degrande@durham.ac.uk"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {YB, 0}, {YT, 0}};

FR$GoldstoneList={S[21], S[22]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

S[21] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[22] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

S[1] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {Q},
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    PropagatorLabel -> Hc,
    Mass -> mhc },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "h0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh1,
    Indices -> {} },

S[3] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh2,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh3,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
mhc[ ___ ] := mhc;
mh1[ ___ ] := mh1;
mh2[ ___ ] := mh2;
mh3[ ___ ] := mh3;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , V[1] , V[1] ] == {{((ca + I*sa)*(I*ca + sa)*(cw*g1 - gw*sw)^2)/2, 0}},

C[ S[3] , S[3] , V[1] , V[1] ] == {{((ca + I*sa)*(I*ca + sa)*(cw*g1 - gw*sw)^2)/2, 0}},

C[ S[4] , S[4] , V[1] , V[1] ] == {{((cb + I*sb)*(I*cb + sb)*(cw*g1 - gw*sw)^2)/2, 0}},

C[ S[1] , -S[1] , V[1] , V[1] ] == {{((cb + I*sb)*(I*cb + sb)*(cw*g1 + gw*sw)^2)/2, 0}},

C[ S[3] , V[1] , V[1] ] == {{(I/2)*(ca*cb + sa*sb)*(cw*g1 - gw*sw)^2*vev, 0}},

C[ S[2] , V[1] , V[1] ] == {{(-I/2)*(cb*sa - ca*sb)*(cw*g1 - gw*sw)^2*vev, 0}},

C[ S[2] , S[4] , V[1] ] == {{-gc7, 0}, {gc7, 0}},

C[ S[3] , S[4] , V[1] ] == {{-gc8, 0}, {gc8, 0}},

C[ S[1] , -S[1] , V[1] ] == {{(-I)*gc9, 0}, {I*gc9, 0}},

C[ -U[4, {e1x1}] , U[4, {e2x1}] , V[4, {e3x2}] ] == {{gc10*SUNF[e3x2, e1x1, e2x1], 0}, {gc10*SUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc11*SUNF[e1x2, e2x2, e3x2]), 0}, {gc11*SUNF[e1x2, e2x2, e3x2], 0}, {gc11*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc11*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc11*SUNF[e1x2, e2x2, e3x2]), 0}, {gc11*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc12*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc12*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc12*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[1] ] == {{I*gc13L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc13R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{I*gc14L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc14R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{gc15L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc15R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{I*gc16L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc16R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[1] ] == {{I*gc17[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{I*gc18L[e1x2, e2x2], 0}, {I*gc18R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{I*gc19L[e1x2, e2x2], 0}, {I*gc19R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{gc20L[e1x2, e2x2], 0}, {gc20R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc21L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc21R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{I*gc22L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc22R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[4] ] == {{gc23L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc23R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[3] ] == {{I*gc24L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc24R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ S[2] , -S[1] , V[1] , V[3] ] == {{(I/2)*cw*g1*gw*(ca*cb + sa*sb), 0}},

C[ S[4] , -S[1] , V[1] , V[3] ] == {{(cw*g1*gw*(cb^2 + sb^2))/2, 0}},

C[ S[3] , -S[1] , V[1] , V[3] ] == {{(I/2)*cw*g1*gw*(cb*sa - ca*sb), 0}},

C[ S[2] , -S[1] , V[3] ] == {{(-I)*gc28, 0}, {I*gc28, 0}},

C[ S[3] , -S[1] , V[3] ] == {{(-I)*gc29, 0}, {I*gc29, 0}},

C[ S[4] , -S[1] , V[3] ] == {{-gc30, 0}, {gc30, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc31, 0}, {I*gc31, 0}, {I*gc31, 0}, {(-I)*gc31, 0}, {(-I)*gc31, 0}, {I*gc31, 0}},

C[ S[2] , S[1] , V[1] , -V[3] ] == {{(I/2)*cw*g1*gw*(ca*cb + sa*sb), 0}},

C[ S[4] , S[1] , V[1] , -V[3] ] == {{-(cw*g1*gw*(cb^2 + sb^2))/2, 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{(I/2)*cw*g1*gw*(cb*sa - ca*sb), 0}},

C[ S[2] , S[1] , -V[3] ] == {{(-I)*gc35, 0}, {I*gc35, 0}},

C[ S[3] , S[1] , -V[3] ] == {{(-I)*gc36, 0}, {I*gc36, 0}},

C[ S[4] , S[1] , -V[3] ] == {{-gc37, 0}, {gc37, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{(gw^2*(ca + I*sa)*(I*ca + sa))/2, 0}},

C[ S[3] , S[3] , V[3] , -V[3] ] == {{(gw^2*(ca + I*sa)*(I*ca + sa))/2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{(gw^2*(cb + I*sb)*(I*cb + sb))/2, 0}},

C[ S[1] , -S[1] , V[3] , -V[3] ] == {{(gw^2*(cb + I*sb)*(I*cb + sb))/2, 0}},

C[ S[3] , V[3] , -V[3] ] == {{(I/2)*gw^2*(ca*cb + sa*sb)*vev, 0}},

C[ S[2] , V[3] , -V[3] ] == {{(-I/2)*gw^2*(cb*sa - ca*sb)*vev, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc44, 0}, {(-I)*gc44, 0}, {(2*I)*gc44, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc45, 0}, {I*gc45, 0}, {I*gc45, 0}, {(-I)*gc45, 0}, {(-I)*gc45, 0}, {I*gc45, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc46, 0}, {(-I)*gc46, 0}, {(2*I)*gc46, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{0, 0}, {I*gc47R[e1x2, e2x2], 0}},

C[ S[2] , S[2] , V[1] , V[2] ] == {{((ca - I*sa)*((-I)*ca + sa)*(cw*gw + g1*sw)*(cw*g1 - gw*sw))/2, 0}},

C[ S[3] , S[3] , V[1] , V[2] ] == {{((ca - I*sa)*((-I)*ca + sa)*(cw*gw + g1*sw)*(cw*g1 - gw*sw))/2, 0}},

C[ S[4] , S[4] , V[1] , V[2] ] == {{((cb - I*sb)*((-I)*cb + sb)*(cw*gw + g1*sw)*(cw*g1 - gw*sw))/2, 0}},

C[ S[1] , -S[1] , V[1] , V[2] ] == {{((cb + I*sb)*(I*cb + sb)*(cw*gw - g1*sw)*(cw*g1 + gw*sw))/2, 0}},

C[ S[3] , V[1] , V[2] ] == {{(-I/2)*(ca*cb + sa*sb)*(cw*gw + g1*sw)*(cw*g1 - gw*sw)*vev, 0}},

C[ S[2] , V[1] , V[2] ] == {{(I/2)*(cb*sa - ca*sb)*(cw*gw + g1*sw)*(cw*g1 - gw*sw)*vev, 0}},

C[ S[2] , S[4] , V[2] ] == {{-gc54, 0}, {gc54, 0}},

C[ S[3] , S[4] , V[2] ] == {{-gc55, 0}, {gc55, 0}},

C[ S[1] , -S[1] , V[2] ] == {{(-I)*gc56, 0}, {I*gc56, 0}},

C[ S[2] , -S[1] , V[3] , V[2] ] == {{(-I/2)*g1*gw*(ca*cb + sa*sb)*sw, 0}},

C[ S[4] , -S[1] , V[3] , V[2] ] == {{-(g1*gw*(cb^2 + sb^2)*sw)/2, 0}},

C[ S[3] , -S[1] , V[3] , V[2] ] == {{(-I/2)*g1*gw*(cb*sa - ca*sb)*sw, 0}},

C[ S[2] , S[1] , -V[3] , V[2] ] == {{(-I/2)*g1*gw*(ca*cb + sa*sb)*sw, 0}},

C[ S[4] , S[1] , -V[3] , V[2] ] == {{(g1*gw*(cb^2 + sb^2)*sw)/2, 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{(-I/2)*g1*gw*(cb*sa - ca*sb)*sw, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc63, 0}, {I*gc63, 0}, {I*gc63, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((ca + I*sa)*(I*ca + sa)*(cw*gw + g1*sw)^2)/2, 0}},

C[ S[3] , S[3] , V[2] , V[2] ] == {{((ca + I*sa)*(I*ca + sa)*(cw*gw + g1*sw)^2)/2, 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((cb + I*sb)*(I*cb + sb)*(cw*gw + g1*sw)^2)/2, 0}},

C[ S[1] , -S[1] , V[2] , V[2] ] == {{((cb + I*sb)*(I*cb + sb)*(cw*gw - g1*sw)^2)/2, 0}},

C[ S[3] , V[2] , V[2] ] == {{(I/2)*(ca*cb + sa*sb)*(cw*gw + g1*sw)^2*vev, 0}},

C[ S[2] , V[2] , V[2] ] == {{(-I/2)*(cb*sa - ca*sb)*(cw*gw + g1*sw)^2*vev, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc70, 0}, {(-I)*gc70, 0}, {(2*I)*gc70, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[1] ] == {{I*gc71*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc72L*IndexDelta[e1x2, e2x2], 0}, {I*gc72R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc73L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc73R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc74L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc74R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc75*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc75*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc76*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc76*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc77[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc78[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc79*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc80*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc81L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc81R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc82L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc82R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc83*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc84L*IndexDelta[e1x2, e2x2], 0}, {I*gc84R*IndexDelta[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc7 -> ((ca*cb + sa*sb)*(cw*g1 - gw*sw))/2,
     gc8 -> ((cb*sa - ca*sb)*(cw*g1 - gw*sw))/2,
     gc9 -> -((cb^2 + sb^2)*(cw*g1 + gw*sw))/2,
     gc10 -> GS,
     gc11 -> -GS,
     gc12 -> -GS^2,
     gc13L[e1x2_, e2x2_] -> -(cb*IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}]),
     gc13R[e1x2_, e2x2_] -> cb*IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc14L[e1x2_, e2x2_] -> -((ca*Conjugate[yd[e2x2, e1x2]])/Sqrt[2]),
     gc14R[e1x2_, e2x2_] -> -((ca*yd[e1x2, e2x2])/Sqrt[2]),
     gc15L[e1x2_, e2x2_] -> (cb*Conjugate[yd[e2x2, e1x2]])/Sqrt[2],
     gc15R[e1x2_, e2x2_] -> -((cb*yd[e1x2, e2x2])/Sqrt[2]),
     gc16L[e1x2_, e2x2_] -> -((sa*Conjugate[yd[e2x2, e1x2]])/Sqrt[2]),
     gc16R[e1x2_, e2x2_] -> -((sa*yd[e1x2, e2x2])/Sqrt[2]),
     gc17[e1x2_, e2x2_] -> sb*Conjugate[yl[e2x2, e1x2]],
     gc18L[e1x2_, e2x2_] -> -((ca*Conjugate[yl[e2x2, e1x2]])/Sqrt[2]),
     gc18R[e1x2_, e2x2_] -> -((ca*yl[e1x2, e2x2])/Sqrt[2]),
     gc19L[e1x2_, e2x2_] -> (sa*Conjugate[yl[e2x2, e1x2]])/Sqrt[2],
     gc19R[e1x2_, e2x2_] -> (sa*yl[e1x2, e2x2])/Sqrt[2],
     gc20L[e1x2_, e2x2_] -> -((sb*Conjugate[yl[e2x2, e1x2]])/Sqrt[2]),
     gc20R[e1x2_, e2x2_] -> (sb*yl[e1x2, e2x2])/Sqrt[2],
     gc21L[e1x2_, e2x2_] -> cb*IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc21R[e1x2_, e2x2_] -> -(cb*IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}]),
     gc22L[e1x2_, e2x2_] -> -((ca*Conjugate[yu[e2x2, e1x2]])/Sqrt[2]),
     gc22R[e1x2_, e2x2_] -> -((ca*yu[e1x2, e2x2])/Sqrt[2]),
     gc23L[e1x2_, e2x2_] -> -((cb*Conjugate[yu[e2x2, e1x2]])/Sqrt[2]),
     gc23R[e1x2_, e2x2_] -> (cb*yu[e1x2, e2x2])/Sqrt[2],
     gc24L[e1x2_, e2x2_] -> -((sa*Conjugate[yu[e2x2, e1x2]])/Sqrt[2]),
     gc24R[e1x2_, e2x2_] -> -((sa*yu[e1x2, e2x2])/Sqrt[2]),
     gc28 -> -(gw*(ca*cb + sa*sb))/2,
     gc29 -> -(gw*(cb*sa - ca*sb))/2,
     gc30 -> -(gw*(cb^2 + sb^2))/2,
     gc31 -> gw*sw,
     gc35 -> (gw*(ca*cb + sa*sb))/2,
     gc36 -> (gw*(cb*sa - ca*sb))/2,
     gc37 -> -(gw*(cb^2 + sb^2))/2,
     gc44 -> -(gw^2*sw^2),
     gc45 -> cw*gw,
     gc46 -> gw^2,
     gc47R[e1x2_, e2x2_] -> sb*yl[e1x2, e2x2],
     gc54 -> -((ca*cb + sa*sb)*(cw*gw + g1*sw))/2,
     gc55 -> -((cb*sa - ca*sb)*(cw*gw + g1*sw))/2,
     gc56 -> -((cb^2 + sb^2)*(cw*gw - g1*sw))/2,
     gc63 -> cw*gw^2*sw,
     gc70 -> -(cw^2*gw^2),
     gc71 -> (-(cw*g1) + gw*sw)/2,
     gc72L -> (-(cw*g1) - gw*sw)/2,
     gc72R -> -(cw*g1),
     gc73L -> (cw*g1 + 3*gw*sw)/6,
     gc73R -> (2*cw*g1)/3,
     gc74L -> (cw*g1 - 3*gw*sw)/6,
     gc74R -> -(cw*g1)/3,
     gc75 -> GS,
     gc76 -> GS,
     gc77[e1x2_, e2x2_] -> (gw*CKM[e1x2, e2x2])/Sqrt[2],
     gc78[e1x2_, e2x2_] -> (gw*Conjugate[CKM[e2x2, e1x2]])/Sqrt[2],
     gc79 -> gw/Sqrt[2],
     gc80 -> gw/Sqrt[2],
     gc81L -> (3*cw*gw - g1*sw)/6,
     gc81R -> (-2*g1*sw)/3,
     gc82L -> (-3*cw*gw - g1*sw)/6,
     gc82R -> (g1*sw)/3,
     gc83 -> (cw*gw + g1*sw)/2,
     gc84L -> (-(cw*gw) + g1*sw)/2,
     gc84R -> g1*sw};

